apiVersion: v1
kind: Service
metadata:
    name: pyrest-service  # The name of the service
spec:
    type: NodePort  # Expose the service on a port on each node
    ports:
        - port: 3050  # Port exposed on the service
          targetPort: 3000  # Port to which the service is forwarded within the pod
          nodePort: 30001
    selector:
        app: pyrest  # The label selector to determine which pods will belong to this service
